language: java

env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

cache:
  directories:
    - $HOME/.jabba/jdk
    - $HOME/.m2

arch:
  - amd64
  - ppc64le
